#define ttn_BITMAP_LOG_OFF      303
#define ttn_BITMAP_LOG_ON       302
#define ttn_BITMAP_EXIT 301
#define ttn_BITMAP_GO   300
#define ttn_ASTRO       911
#define ttn_LOGO        910
#define DI_OUTPUTTITLE_BOOL     20003
#define DI_OUTPUTTITLE_STR      20005
#define DI_OUTPUTTITLE  20001
#define DI_MENULIST     102
#define DI_NUMEDIT      104
#define ttn_MENU1       122
#define MI_LOGFILEOFF   106
#define MI_LOGFILEON    105
#define MI_ABOUT        103
#define MI_TEXTEDIT     101
#define MI_CLS  102
#define MI_MEMORY       104
#define ttn_CURSOR      126
#define ttn_ICON        128
#define MI_START        144
#define MI_STOP         146
#define DI_NO           162
#define DI_YES          164

#define NUMLINES      25      /* Output */
#define MAXLINELENGTH 180

#define TEXTTITLESIZE  80     /* for requesters */
#define INPUTTEXTSIZE  30     /* for input      */
#define MITEMNUM 50
#define MITEMLENGTH 70
/* All these are definitions for MSWINDOWS compilation */
